services:
  - type: web
    name: ponto-real-go
    runtime: go
    # Build from root directory
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
      - key: GO_VERSION
        value: 1.25.0
      - key: GIN_MODE
        value: release
